### ISSUE TITLE
no default font found - need to install manually

### ISSUE THREAD

**Issue by Lanjelin** [codesnap-rs/codesnap#43]
Installed using howbrew on headless Arch Linux. Running the following `codesnap --output "./out.png" -f ./main.py` thows the error

```bash
⣯ Generating...
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cosmic-text-0.12.1/src/shape.rs:251:33:
no default font found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Prepending `RUST_BACKTRACE=full`
```bash
⣯ Generating...
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cosmic-text-0.12.1/src/shape.rs:251:33:
no default font found
stack backtrace:
   0:     0x6032ef83a6ba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x6032ef861ee3 - core::fmt::write::h7550c97b06c86515
   2:     0x6032ef836923 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x6032ef83a502 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x6032ef83b5ec - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x6032ef83b432 - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x6032ef83bbc7 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   7:     0x6032ef83ba5a - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   8:     0x6032ef83ab99 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
   9:     0x6032ef83b6ec - rust_begin_unwind
  10:     0x6032ef3c7330 - core::panicking::panic_fmt::h0c3082644d1bf418
  11:     0x6032ef3c730b - core::option::expect_failed::h95d2432053ef5ebb
  12:     0x6032ef66159f - cosmic_text::shape::Shaping::run::h2e215c4424c7ecc6
  13:     0x6032ef663690 - cosmic_text::shape::ShapeWord::new_in_buffer::h1adbec62b1056bd8
  14:     0x6032ef663c2c - cosmic_text::shape::ShapeSpan::new_in_buffer::h6130dcfd94d9d8fd
  15:     0x6032ef664875 - cosmic_text::shape::ShapeLine::new_in_buffer::hf819e4749a78e0f8
  16:     0x6032ef6518cd - cosmic_text::buffer_line::BufferLine::shape_in_buffer::h31bac8971caef697
  17:     0x6032ef6519e6 - cosmic_text::buffer_line::BufferLine::layout_in_buffer::h264207930024cc98
  18:     0x6032ef643269 - cosmic_text::buffer::Buffer::shape_until_scroll::h10703dade11252be
  19:     0x6032ef44f330 - cosmic_text::buffer::Buffer::set_rich_text::h6d42f44dd7f76d17
  20:     0x6032ef462349 - codesnap::utils::text::FontRenderer::draw_text::hf1d7d514deee6895
  21:     0x6032ef4344ad - <codesnap::components::editor::code::Code as codesnap::components::interface::component::Component>::draw_self::hf6979915764fb0db
  22:     0x6032ef435cdb - codesnap::components::interface::component::Component::draw::h67ddef3723194cfc
  23:     0x6032ef435a01 - codesnap::components::interface::component::Component::draw::h6329e9828026ccc5
  24:     0x6032ef4370ba - codesnap::components::interface::component::Component::draw::hdc11f9468ea204c5
  25:     0x6032ef4370ba - codesnap::components::interface::component::Component::draw::hdc11f9468ea204c5
  26:     0x6032ef4370ba - codesnap::components::interface::component::Component::draw::hdc11f9468ea204c5
  27:     0x6032ef44d4c0 - codesnap::components::interface::component::Component::draw::h7dc4e7ca39e63e24
  28:     0x6032ef44bb9d - codesnap::components::container::Container::draw_root::h33abef6137f123f3
  29:     0x6032ef446250 - codesnap::snapshot::image_snapshot::ImageSnapshot::from_config::hf2e4282b79a321c1
  30:     0x6032ef462226 - codesnap::config::SnapshotConfig::create_snapshot::h9fb9c098914ebccf
  31:     0x6032ef3cdc2f - codesnap::main::hb03bb9e664c5f815
  32:     0x6032ef3eec93 - std::sys::backtrace::__rust_begin_short_backtrace::h24b52a3082aa1f33
  33:     0x6032ef3f36a9 - std::rt::lang_start::{{closure}}::h6797f7c7800e880a
  34:     0x6032ef82d39e - std::rt::lang_start_internal::h1c66660c99c8424c
  35:     0x6032ef3e1765 - main
  36:     0x78c48d390e08 - <unknown>
  37:     0x78c48d390ecc - __libc_start_main
  38:     0x6032ef3c7ad5 - _start
  39:                0x0 - <unknown>
```

Manually downloading the [FireCode Nerd Font](https://www.nerdfonts.com/font-downloads) and running with the command `codesnap --output "./out.png" -f ./main.py --fonts-folder "/home/username/font`, and it all works as expected.  

I've done everything with the default generated config, `Pacifico` for watermark works.

Installing through homebrew on unraid/slackware does not have this issue though.

**Comment by mistricky** [comment]
@Lanjelin the latest version should be fixed this issue
